# Default values for apisix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-beijing.aliyuncs.com/tinywan/apisix
  tag: alpine
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9080
  ssl:
    enabled: ture
    http2Enabled: true
    port: 9443
    ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2 TLSv1.3"
    ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA"
  enableHeartbeat: false
  enableDebug: false
  enableIpv6: false
  configCenter: etcd
  streamProxyEnabled: false
  router:
    http: 'radixtree_uri'
    ssl: 'radixtree_sni'
  plugins:
    - example-plugin
    - limit-req
    - limit-count
    - limit-conn
    - key-auth
    - prometheus
    - node-status
    - jwt-auth
    - zipkin
    - ip-restriction
    - grpc-transcode
    - serverless-pre-function
    - serverless-post-function
    - openid-connect
    - proxy-rewrite
  stream_plugins:
    - mqtt-proxy

config:
  real_ip_header: "X-Real-IP"
  real_ip_from:
    - 127.0.0.1
    - 'unix:'
  stream_proxy:
    tcp:
      - 9100
      - 9101
    udp:
      - 9200
      - 9211
  dns_resolver:
    - kube-dns.kube-system.svc.cluster.local

admin:
  enabled: true
  servicePort: 9180
  serviceType: ClusterIP
  allows:
    enabled: false
    list:
      - 127.0.0.0/24
      - "::/64"

nginx:
  config:
    error_log: /dev/stderr
    error_log_level: "error"
    event:
      worker_connections: 10620
    http:
      access_log: /dev/stdout
      keepalive_timeout: 60s
      client_header_timeout: 60s
      client_body_timeout: 60s
      send_timeout: 10s

etcd:
  enabled: true
  customHost: ""
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 1                      # 1 seconds

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

waitImage:
  repository: quay.io/coreos/etcd
  tag: v3.3.17
  pullPolicy: IfNotPresent

# override values of etcd-operator's values.yaml file
etcdoperator:
  enabled: true
  customResources:
    createEtcdClusterCRD: true
  etcdOperator:
    readinessProbe:
      enabled: true
    livenessProbe:
      enabled: true
  etcdCluster:
    version: v3.3.17
    pod:
      env:
        - name: ETCD_ENABLE_V2
          value: true
      ## Antiaffinity for etcd pod assignment
      ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
      antiAffinity: false
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      ## Node labels for etcd pod assignment
      ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
      nodeSelector: {}
      securityContext: {}
      tolerations: []
