apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apisix.fullname" . }}
  labels:
{{ include "apisix.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "apisix.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "apisix.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      {{- include "apisix.wait-for-etcd" . | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
            - name: http-admin
              containerPort: 9180
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /apisix/status
              port: http
          readinessProbe:
            httpGet:
              path: /apisix/status
              port: http
          volumeMounts:
            - mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
              name: apisix-custom-config-file-volume
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: apisix-custom-config-file-volume
          configMap:
            name: {{ .Release.Name }}-apisix-custom-config-file-blocks
