apiVersion: v1
kind: Service
metadata:
  name: {{ include "apisix.fullname" . }}-gateway
  labels:
{{ include "apisix.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "apisix.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
